language: node_js
sudo: required
node_js:
- '4'
install:
- npm install -g mocha babel
script:
- npm run test
deploy:
  provider: npm
  email: gabriel.juchault@gmail.com
  api_key:
    secure: Z7+RRKm4vibhNzTMhvdVjzPXx6ncFqwsqtyXwvARFHKvpu8mPpzVI+BJZBKwvkwIiLcOe9ikYqwWFn0rDTU5BnoQGhRkBmtex+hGVbuxYJc/UW+q4mUT0uSX6602Cmt9leXBOhoSPxk8u7epygSZ8X4IdHXY/v5PG9uOplzh8UfZUXemOhqOEQFcQzOexTuIrecMQ6kdSrw95+MCdCL/qHkQmL2UeHDfpovushv/Z2D8scRHoWoFgmb/skdhlFLaLypL0Ec0DNuuRUrelaDXhY4R7UzPt6Xthrh1Xevp0naeH2PFkyv/j4pW4ErVM8UR1m7VgbG/0Ox9YEtMlF+8CWNpllcWMRzuNaqva8cMaROYPKDXPASh+i6x6EIofUsE5n7QV7Ey8YVq+i9mNkDxiy1W2r0tw84KeBsWafbOZh/F5TvOiy1mZtmv7y8HFlNE25jIAoqp6JE+Rlw15JJOruT1nK7xdd+sCFbq3JW4egW+153XKK7ZFuodV2jbAdo7NJ0gU1ej4TqPMZooKbNeJcAkJtWjdnRboNKsEa2sgHbyyLodiLidRH71WJqpTX+9vLzWQg2VOz1Yoz0u941A41HHbYsWhM2j8EVyAjZukhV9W0GqaBMWVlJb829ftRYPzXPlXPt6p62acV3l+PcMDh0kWWolnW3cBO4ZRKnqnYA=
  on:
    repo: gjuchault/schedulerjs
